import { Session } from "./types";

export const mockSessions: Session[] = [
  {
    id: "1",
    type: "wood carving",
    tools: ["sloyd knife", "strop", "sandpaper"],
    mood: ["Calm", "Focused"],
    duration: 90,
    notes: "Worked on spoon shape.",
    timestamp: "2025-06-11T14:20:00.000Z",
  },
  {
    id: "2",
    type: "painting",
    tools: ["acrylic paints", "palette knife"],
    mood: ["Flowing", "Playful"],
    duration: 120,
    notes: "Experimented with texture.",
    timestamp: "2025-06-10T18:00:00.000Z",
  },
  {
    id: "3",
    type: "blind drawing",
    tools: ["charcoal", "newsprint"],
    mood: ["Present", "Curious"],
    duration: 30,
    notes: "",
    timestamp: "2025-06-09T08:45:00.000Z",
  },
  {
    id: "4",
    type: "wood carving",
    tools: ["gouge", "mallet"],
    mood: ["Focused", "Peaceful"],
    duration: 60,
    notes: "Tried new carving pattern.",
    timestamp: "2025-06-07T10:00:00.000Z",
  },
  {
    id: "5",
    type: "painting",
    tools: ["oil paints", "brushes"],
    mood: ["Frustrated", "Introspective"],
    duration: 75,
    notes: "Struggled with composition.",
    timestamp: "2025-06-05T17:30:00.000Z",
  },
  {
    id: "6",
    type: "blind drawing",
    tools: ["pen", "sketchbook"],
    mood: ["Playful", "Nostalgic"],
    duration: 20,
    notes: "Freeform faces.",
    timestamp: "2025-06-04T19:15:00.000Z",
  },
  {
    id: "7",
    type: "painting",
    tools: ["watercolors", "fine liner"],
    mood: ["Calm", "Curious"],
    duration: 50,
    notes: "",
    timestamp: "2025-06-02T15:00:00.000Z",
  },
];
